# Generated by Django 4.1.2 on 2022-11-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRoadStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nb_objects', models.IntegerField(verbose_name='Number of objects')),
                ('nb_cars', models.IntegerField(verbose_name='Number of cars')),
                ('nb_persons', models.IntegerField(verbose_name='Number of persons')),
                ('nb_motorcycles', models.IntegerField(verbose_name='Number of motorcycles')),
                ('nb_bicycles', models.IntegerField(verbose_name='Number of bicycles')),
                ('nb_intake_dates', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
